
wallpaper {
 monitor = DP-1
 path = ~/Pictures/dumb_rice/wallpapers/animebg.png
 fit_mode = cover
}
# 
wallpaper {
 monitor = HDMI-A-1
 path = ~/Pictures/dumb_rice/wallpapers/tall.jpeg
 fit_mode = cover
}
