# motherfucking keybinds
# mostly for scrips
$mainMod = SUPER # Sets "Windows" key as main modifier

bind = $mainMod, F1, exec, ~/.config/hypr/scrips/modes.fish
bind = $mainMod, F2, exec, ~/.config/hypr/scrips/focus.fish
